### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by JungHY** [onlytailei/pytorch-flownet2#1]
i got Error on test.py

this is my error message when i run test.py

Traceback (most recent call last):
  File "test.py", line 18, in <module>
    print test_layer(a,b)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jhyeup/PycharmProjects/pytorch-flownet2/nets/flownetC.py", line 70, in forward
    sub_x_1 = x_1.sub(mean_x_1.expand_as(x_1))
RuntimeError: The expanded size of the tensor (3) must match the existing size (30) at non-singleton dimension 3

**Comment by zhhezhhe** [comment]
I got the same error. @JungHY

**Comment by cnuzh** [comment]
Hi,do you solve the problem,now? @JungHY @zhhezhhe
